# Generated by Django 4.1.3 on 2022-11-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='des',
            new_name='desc',
        ),
    ]
