# Generated by Django 4.1.3 on 2022-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbt', '0002_rename_des_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.TextField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
