# Generated by Django 4.1.3 on 2022-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbt', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
